# Development overrides - inherits from application.yml
server:
  http-port: 8080
  https-port: 8443
  context-path: /
  api-path: /api/*
  static-resource-path: static
  welcome-files: index.html,home.html
  idle-timeout: 30000
  stop-timeout: 10000
  ssl:
    keystore:
      path: ssl/keystore.p12
      password: pass123
      manager-password: pass123

security:
  jwt:
    secret: devsecret123
    algorithm: HS256
    expiration-minutes: 15
    verification-url: https://rapidapi.com/rapidapi/api/rapidapi-demo
  crypto:
    secret: devsecret123
    algorithm: AES
  crypto-provider: conscrypt

database:
  url: jdbc:h2:mem:devdb
  username: dev
  password: dev123

datasource:
  url: jdbc:h2:mem:devdb
  username: dev
  password: dev123
  pool:
    type: HIKARI
    max-size: 10
    min-size: 2
    connection-timeout: 30000
    idle-timeout: 600000

logging:
  level: DEBUG

app:
  name: "RapidApi Demo App"
  version: "1.0.0-SNAPSHOT"
  description: "Development environment for RapidApi App"
  environment: "development"

business:
  products:
    max-per-page: 20
    validation-enabled: true
    max-price: 5000.00
    default-currency: USD

api:
  version: v1
  rate-limit:
    per-minute: 60
  request:
    max-size-mb: 5
  cors:
    enabled: true
    allowed-origins: "http://localhost:3000,http://localhost:8080"

template:
  prefix: templates/
  suffix: .html
  mode: HTML5
  cacheable: false
  encoding: UTF-8
  cache:
    ttl-ms: 3600000